language: python
python:
  - "2.7"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: 
    - "python setup.py install"
    - "pip install -e '.[selenium]'"
# command to run tests
script: python setup.py test
